### ISSUE TITLE
Does not compile using FFMPEG 5.1.1-3 due to deprecated functions

### ISSUE THREAD

**Issue by ghost** [JoelZimmerman/c64tapwav#1]
`audioreader.cpp:41:17: error: ‘av_free_packet’ was not declared in this scope; did you mean ‘av_new_packet’?
   41 |                 av_free_packet(pkt);
      |                 ^~~~~~~~~~~~~~
      |                 av_new_packet
`

`
audioreader.cpp: In function ‘int {anonymous}::decode_packet(const char*, AVCodecContext*, SwrContext*, AVFrame*, AVPacket*, int*, std::vector<float>*)’:
audioreader.cpp:80:20: error: ‘avcodec_decode_audio4’ was not declared in this scope; did you mean ‘avcodec_decode_subtitle2’?
   80 |         int len1 = avcodec_decode_audio4(codec_ctx, audio_frame, got_frame, packet);
      |                    ^~~~~~~~~~~~~~~~~~~~~
      |                    avcodec_decode_subtitle2
`

`
audioreader.cpp: In function ‘bool read_audio_file(const char*, std::vector<float>*, int*)’:
audioreader.cpp:99:9: error: ‘av_register_all’ was not declared in this scope
   99 |         av_register_all();
      |         ^~~~~~~~~~~~~~~
audioreader.cpp:116:45: error: ‘AVStream’ {aka ‘struct AVStream’} has no member named ‘codec’
  116 |                 if (format_ctx->streams[i]->codec->codec_type == AVMEDIA_TYPE_AUDIO) {
      |                                             ^~~~~
audioreader.cpp:126:88: error: ‘AVStream’ {aka ‘struct AVStream’} has no member named ‘codec’
  126 |         AVCodec *codec = avcodec_find_decoder(format_ctx->streams[audio_stream_index]->codec->codec_id);
      |                                                                                        ^~~~~
audioreader.cpp:134:86: error: ‘AVStream’ {aka ‘struct AVStream’} has no member named ‘codec’
  134 |         if (avcodec_copy_context(codec_ctx, format_ctx->streams[audio_stream_index]->codec) != 0) {
      |                                                                                      ^~~~~
audioreader.cpp:134:13: error: ‘avcodec_copy_context’ was not declared in this scope; did you mean ‘avcodec_free_context’?
  134 |         if (avcodec_copy_context(codec_ctx, format_ctx->streams[audio_stream_index]->codec) != 0) {
      |             ^~~~~~~~~~~~~~~~~~~~
      |             avcodec_free_context
`
